import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Auth0Provider } from "@auth0/nextjs-auth0";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Auth0Provider>
          {/* Navigation Bar */}
          <nav
            style={{
              backgroundColor: "#A33",
              padding: "1rem",
			  justifyContent: "center", // centers the nav items
              display: "flex",
              gap: "6rem",
            }}
          >
            <a href="/" style={{ color: "#fff", textDecoration: "none" }}>Home</a>
            <a href="/game" style={{ color: "#fff", textDecoration: "none" }}>PvE</a>
            <a href="/auth" style={{ color: "#fff", textDecoration: "none" }}>PvP</a>
            {/* Add more links here */}
          </nav>
          
          {/* Page Content */}
          {children}
        </Auth0Provider>
      </body>
    </html>
  );
}